version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Mypass123
    platform: linux/amd64
    ports:
      - "1433:1433"
  
  postgresql:
    image: postgres:15.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Mypass123

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Mypass123
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
