version: '3.8'

services:

  sqlpipe:
    build:
      context: .
      dockerfile: sqlpipe.dockerfile
    container_name: sqlpipe
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 8G

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Mypass123
    platform: linux/amd64
    volumes:
      - ./setup-sql/mssql.sql:/setup.sql
    command: >
      /bin/bash -c "
        export TZ=US/Pacific
        /opt/mssql/bin/sqlservr &
        sleep 25;
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Mypass123' -d master -i /setup.sql
        tail -f /dev/null
      "
    ports:
      - "1433:1433"
    deploy:
      resources:
        limits:
          memory: 8G

  postgresql:
    image: postgres:15.3
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Mypass123
      TZ: America/Los_Angeles
    volumes:
      - ./setup-sql/postgresql-simple.sql:/docker-entrypoint-initdb.d/setup-1.sql
      - ./setup-sql/postgresql-complex.sql:/docker-entrypoint-initdb.d/setup-2.sql
    deploy:
      resources:
        limits:
          memory: 8G

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Mypass123
      - TZ=America/Los_Angeles
    ports:
      - "3306:3306"
    volumes:
      - ./setup-sql/mysql.sql:/docker-entrypoint-initdb.d/setup.sql
    deploy:
      resources:
        limits:
          memory: 8G
    command: --local-infile=1


  oracle:
    image: oracle:21.3.0
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=Mypass123
      - NLS_CHARACTERSET=AL32UTF8
    volumes:
      - ./setup-sql/oracle.sql:/opt/oracle/scripts/startup/setup.sql
    deploy:
      resources:
        limits:
          memory: 8G